### ISSUE TITLE
Not working in 4.1 beta 2

### ISSUE THREAD

**Issue by dbebber** [elmasse/Ext.i18n.Bundle#1]
using Test sample included with Bundle getting this in 4.1

me.createFieldAccessExpression is not a function
[Break On This Error] code.push(' dest', ...on(field, varName, 'source'), ';\n');
ext-all-debug.js (line 19350)

4.0.7 works fine
